spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.50.116/sell?characterEncoding=utf-8&usingSSL=false
  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell

wechat:
  mpAppId: wxdb309ca9b6cab881
  mpAppSecret: 415c3a6c2c80840c53164e7f3e2c6369